/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import javafx.application.Application;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Application.launch(controller.GeneralController.class, args);
    }
}
